export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_BY_ID = 'GET_PRODUCTS_BY_ID';
export const CLEAR_PRODUCT_DETAILS = 'CLEAR_PRODUCT_DETAILS';
export const ADD_ID_PRODUCT_TO_CART = 'ADD_ID_PRODUCT_TO_CART';